version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: .
        target: /workspace
    stdin_open: true
    tty: true
