version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: container/front-dev/Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - ../..:/workspace:cached
      - /workspace/node_modules
    stdin_open: true
    tty: true
